### ISSUE TITLE
Broken Websocket due to authentication

### ISSUE THREAD

**Issue by vwiencek** [syncany/syncany-plugin-simpleweb#1]
It seems that Websocket internal handler (/wpi/ws) now requires authentication (simpleweb plugin seems broken ...).

For GUI purposes, I also need to connect and authenticate to websocket daemon but I cannot find any suitable java library for that ...... any ideas ?

**Comment by pimotte** [comment]
Are you testing this in Chrome or Firefox? Firefox should probably work, Chrome is a known issue: https://github.com/syncany/syncany/issues/176

**Comment by vwiencek** [comment]
I'm testing from safari and an external ws tool (tyrus) ....

Ws requires authentication ? 
-----Original Message-----

**Comment by pimotte** [comment]
From the syncany client side, https://github.com/syncany/syncany/blob/develop/syncany-lib/src/main/java/org/syncany/operations/daemon/WebServer.java#L143 and https://github.com/syncany/syncany/blob/develop/syncany-lib/src/main/java/org/syncany/operations/daemon/WebServer.java#L246 allow connecting to /api/ws

I started working on that, then discovered that chrome didn't support basic authentication for websockets and dropped it, because Philipp was still working on the https stuff. The simplewebplugin hould work for firefox, and undertow is the library we use in -lib for connecting to the websockets, so that should suffice for the GUI as well.

**Comment by vwiencek** [comment]
Ok thx.

-----Original Message-----

**Comment by vwiencek** [comment]
I think undertow has no websocket client ....
I'll try jetty one 
-----Original Message-----
From: "Vincent Wiencek" vwiencek@gmail.com
Date: Mon, 29 Sep 2014 05:56:02 
To: syncany/syncany-plugin-simplewebreply@reply.github.com
Reply-To: vwiencek@gmail.com
Subject: Re: [syncany-plugin-simpleweb] Broken Websocket due to authentication (#1)

Ok thx.

-----Original Message-----

**Comment by binwiederhier** [comment]
It must have. It's surely included in the packages we already have.jetty is too heavy.

**Comment by binwiederhier** [comment]
https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/websockets/client/WebSocketClient.java

Hm? Let me know if the authentifixation stuff gives you too much trouble. Maybe there is another way.

**Comment by vwiencek** [comment]
hum.... difficult to figure out how undertow client works ....

https://github.com/vwiencek/syncany/blob/feature/simplegui/syncany-gui/src/main/java/org/syncany/gui/WebSocket.java

On Mon, Sep 29, 2014 at 8:27 AM, Philipp C. Heckel <notifications@github.com

> wrote:
> 
> https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/websockets/client/WebSocketClient.java
> 
> Hm? Let me know if the authentifixation stuff gives you too much trouble.
> Maybe there is another way.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/syncany/syncany-plugin-simpleweb/issues/1#issuecomment-57121264
> .

## 

Vincent Wiencek
vwiencek@gmail.com

**Comment by binwiederhier** [comment]
If you google undertow examples, a few pop up; also: https://github.com/undertow-io/undertow/blob/5bdddf327209a4abf18792e78148863686c26e9b/core/src/test/java/io/undertow/websockets/client/version13/WebSocketClient13TestCase.java

**Comment by binwiederhier** [comment]
Also: `wss://`, not `ws://`.

**Comment by vwiencek** [comment]
finally GOT IT WORKING

Still need to update simpleweb rest end point (getfiletreeresponse ....)

On Mon, Sep 29, 2014 at 2:44 PM, Philipp C. Heckel <notifications@github.com

> wrote:
> 
> Also: wss://, not ws://.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/syncany/syncany-plugin-simpleweb/issues/1#issuecomment-57154730
> .

## 

Vincent Wiencek
vwiencek@gmail.com

**Comment by binwiederhier** [comment]
Just out of curiosity: You're doing the GUI or the web client?

**Comment by vwiencek** [comment]
Gui
But I had to understand websocket .... 
-----Original Message-----

**Comment by binwiederhier** [comment]
We accidentally continued the discussion here instead of i [the original thread](https://github.com/syncany/syncany/issues/204). I'll close  this thread and we'll continue the discussion there.
