### ISSUE TITLE
Plugin does not work for properly-configured remote hosts

### ISSUE THREAD

**Issue by inequation** [syncany/syncany-plugin-simpleweb#2]
When trying to access the web interface from a different machine (after setting `<bindAddress>0.0.0.0</bindAddress>` in the daemon config), it won't work. Chrome's console says the websocket is closed. Here's the entire log:

```
Application.class.js:50 <listWatchesRequest>
  <id>3789898</id>
</listWatchesRequest>
Tree.class.js:46 load_node
Application.class.js:50 <getFileTreeRequest>
  <id>5617257</id>
  <root></root>
  <prefix></prefix>
  <date></date>
</getFileTreeRequest>
Application.class.js:52 WebSocket is already in CLOSING or CLOSED state.
https://brixpro:8443/ Failed to load resource: net::ERR_CACHE_MISS
```

`brixpro` is the hostname of the machine I'm trying to access.

**Comment by pimotte** [comment]
There are some known problems with Chrome (https://github.com/syncany/syncany/issues/176). I'm not entirely sure if this is the same error as I ran into there. (I suspect it is.) Can you try with Firefox?

**Comment by inequation** [comment]
Just tried. On Firefox I'm getting #3, for both remote and local access.

**Comment by binwiederhier** [comment]
See #3 and https://github.com/syncany/syncany/issues/207.
